### ISSUE TITLE
Meetup.com Affiliations

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-docs#10]
## Type of Change
- [ ] New Documentation
- [ ] Update to existing documentation
- [x] Other (please clarify below)

This is a "product" question, to determine what Meetup.com groups the website should launch with.

## Summary

Current considerations
1.  Kenzan Hack Night
1.  ProvJS

Looking for thoughts on others

On a related note, are there any thoughts on creating a "perpetual" invite link to the PVD Geeks Slack team?

**Comment by kpisano** [comment]
Re: Meetup Groups- I thought it would be a good idea to set up some general parameters, feel free to amend- 
Meetups that operate in RI with a STEAM related mission, schedule events at least a few times a year (and have had an event in the 2017 to get started), and have an active community (approx. 10 people rsvp'd to their last few events - or other expectations based on size and theme)

It would also make sense that we'd let them know they'll be included in this project. 

Searching for Tech Meetups within 25miles of PVD and meet the above parameters:
1. Girl Develop It Providence
2. Tech Collective Meetups
3. MojoTech Meetups
4. Rhode Island Makers, MicroControllers, and Robotics
5. Providence UX Meetup
6. <Intracity> Geeks
7. The Wordpress RI Meetup Group

@bjepson Given that PVD Geeks encompasses much more than 'Tech', what other keywords or Meetups should we include?

**Comment by thescientist13** [comment]
Thanks for the awesome list @kpisano !  🙏 

My initial plan based on the [Technical Architecture](https://github.com/ProvidenceGeeks/website-docs/wiki/Technical-Architecture#meetupcom) is that this list would be "curated" / hardcoded, in the sense that the backend would be configured to only pull in data from Meetup.com  for those groups that are defined in a list somewhere (at least for this initial MVP).  

This _could_ eventually be handled by our CMS / Blog API down the road to make updates easier by admins (e.g. PVD Geeks themselves) without having to make a code change to update the list, but I think a fixed list for now makes for a more achievable initial goal.

**Comment by bjepson** [comment]
@kpisano, thanks! I'm comfortable casting as wide a net as we have available for meetups. It might make sense to filter for groups who don't have their own website, which would mostly catch groups who use Facebook or Meetup. There is also the WebDevRI Meetup.

On the question of a perpetual Slack invite link, Slack doesn't allow that for some reason. There is some way to programmatically generate invites (see https://github.com/outsideris/slack-invite-automation), but that could lead to a lot of spam.

**Comment by thescientist13** [comment]
great, thanks for the insight on both those issue @bjepson !

**Comment by thescientist13** [comment]
Thanks for the discussion and feedback @kpisano and @bjepson !
