### ISSUE TITLE
document Release Procedure

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-docs#23]
## Type of Change
- [x] New Documentation
- [ ] Update to existing documentation
- [ ] Other (please clarify below)

## Summary

1. Intro
1. Issue Workflows
1. Tagging / Release Notes
1. Frontend
1. Backend

**Comment by thescientist13** [comment]
should include Gitflow (e.g. develop and master branches)

**Comment by thescientist13** [comment]
Docs posted
https://github.com/ProvidenceGeeks/website-docs/wiki/Release-Management

As you can see, not everything is entirely automated, but that might have to wait until sprint 3, like https://github.com/ProvidenceGeeks/website-api-events/issues/8 and https://github.com/ProvidenceGeeks/website-api-posts/issues/4

**Comment by saimatsumoto** [comment]
thank you @thescientist13 , will there be a set deployment schedule? 
Other than that, I don't have anything to add to this.

**Comment by thescientist13** [comment]
Good call @saimatsumoto !  I will add a section about that.

**Comment by thescientist13** [comment]
Added more docs around procedure, best practices, and general notes
https://github.com/ProvidenceGeeks/website-docs/wiki/Release-Management/_compare/6b68737990b1fc14a3efaa68e2a011495e7d0d38...ab18a50b7613832d7f20971cbe0609e0df4116c5
