### ISSUE TITLE
Add Issue Transition section to Onboarding Guide

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-docs#24]
## Type of Change
- [x] Update to existing documentation

## Summary
1. Set a standard issue flow  
2. Add Issue Status Transition section to [Onboarding Guide](https://github.com/ProvidenceGeeks/website-docs/wiki/Onboarding-Guide)
3. Explain what each state of status means 

## Proposed changes
To add below to Onboarding Guide:

#### Issue Status Transition
To ensure an effective task tracking, please use below as a guide on how to move issues via swim-lane in a project board:
* TODO: development has not started.
* IN PROGRESS: development work is initiated and in progress.
* IN REVIEW: development work is completed and PR is submitted.
* TEST: PR is merged by the maintainers and ready for Testing. 
       1. This step may not be applicable for certain tasks, such as platform setups and discovery work, etc.
       2. "Testing" at this state refers to Integration/E2E testing while unit test should be done prior to this.
* DONE: Test passed in both Development and Production environments.

Relates to #7

**Comment by thescientist13** [comment]
Thanks @saimatsumoto !

Please include your proposed changes in the description when they are ready for review!

**Comment by saimatsumoto** [comment]
@thescientist13 @kpisano I'd appreciate it if you can review this. Thank you!

**Comment by kpisano** [comment]
@saimatsumoto from my perspective this looks great and will be really helpful to have in the onboarding guide. @thescientist13 may have more technical thoughts. Thanks!

**Comment by thescientist13** [comment]
@saimatsumoto 
I think a couple good things to add would be the ownership of transitioning an issue into each state and ensure proper assignee roles.  I think it might be good captured as table?

| STATE     |   Who Should Transition | Assignee   | 
| ------------- | -------- | ------ |
| TODO | N / A | Contributor |
| IN PROGRESS | Contributor | Contributor |
| IN REVIEW | Contributor | Team Lead |
| TEST | Team Lead | Tester / Product Owner |
| DONE | Tester / Product Owner | Tester / Product Owner |

**Comment by saimatsumoto** [comment]
@thescientist13 That looks great and more intuitive. Thank you for the great tip!

**Comment by saimatsumoto** [comment]
| State             | Who Transitions           | Assignee    | Status   |
| --------------- | -------------------------- | ------------- | --------- |
| TODO             | N/A                                | Contributor  |Task within the sprint; development did not start|
| IN PROGRESS  | Contributor                   | Contributor |dev work is initiated and in progress|
| IN REVIEW      | Contributor                    | Team Lead   |dev work is completed and PR is submitted|
| TEST           | Team Lead | Tester/Product Owner |PR is merged by the maintainer and ready for Testing|
| DONE| Tester/Product Owner | Tester/Product Owner|Test passed in both Development and Production environments.| 

* Note 1. "TEST" step may not be applicable for certain tasks, such as platform setups and discovery work, etc.
* Note 2. "TEST" at this state refers to Integration/E2E testing while unit test should be done prior to this.

@thescientist13 @kpisano Above will be the final form of update^ any additional thoughts?

**Comment by thescientist13** [comment]
@saimatsumoto 
I think issue this can be closed now?
