### ISSUE TITLE
Document Unit/Integration testing strategy

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-docs#25]
[Testing Guide wiki page](https://github.com/ProvidenceGeeks/website-docs/wiki/Testing-Guide)

## Type of Change
- [x] New Documentation
- [ ] Other (please clarify below)

## Summary
- [x] Establish philosophy and strategy
- [x]  Scope of the test
- [x] Tool(s) used
- [ ] Test cases / Acceptance Criteria

**Comment by saimatsumoto** [comment]
@thescientist13 @ekrasner1 @kpisano Please let me know if see anything else to be added.

**Comment by thescientist13** [comment]
Looks like a good start to me @saimatsumoto !

**Comment by saimatsumoto** [comment]
@thescientist13 Will you please review?
* What is the best way to document test cases/A.C. for Unit/Integration on this wiki page? (Does "Expectation" cover it at high level? is that sufficient?)
* What is the tool we use for integration, jest as well?

**Comment by thescientist13** [comment]
> What is the best way to document test cases/A.C. for Unit/Integration on this wiki page? (Does "Expectation" cover it at high level? is that sufficient?)

I think what you have is good!

> What is the tool we use for integration, jest as well?

Jest only applies to JavaScript projects, so that would only include **website-frontend** and **website-lambda-*** projects.  On the backend for Java projects, JUnit is being used.
