### ISSUE TITLE
Application Design updates for Mobile  

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-docs#26]
## Type of Change
- [ ] New Documentation
- [x] Update to existing documentation
- [ ] Other (please clarify below)

## Summary
An Application Design is helpful for establishing the basic features, users stories, and look and feel of the project. This issue will strictly track the mobile design specification.  

Overview
Pages
Components
Services
The application design should have screens and images and link out to more technical documentation where appropriate.

**Comment by saimatsumoto** [comment]
TODOs:
- [x] Create mobile design for Homepage, Events List, Blog Posts, and Blog Details @ekrasner1 
- [x] Confirm requirements @ekrasner1 @saimatsumoto
- [x] Document into [Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design)

Due by 10/27

**Comment by saimatsumoto** [comment]
@ekrasner1 @thescientist13 @kpisano Please review the Application Design and share any final thoughts. 
There must be some more things to be improved/updated.

**Comment by thescientist13** [comment]
Looks good really good @saimatsumoto!!!  🎉 ❤️ 🎉 

Did have a couple feedback items:
1.  It might be a little more readable to list out the [breakpoints](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#styleguide) using bullets  E.g.
> - Tablet / Desktop: > 320px
> - Mobile:  <= 320px 

2. I think something happened with the formatting, I had all the list under the Capabilities section of each page / component indented so the list of A.C. would show as nested.  Did that get undone?  Could we do that?  I think it helps make it easier to read when that list is indented

**Comment by saimatsumoto** [comment]
Thank you @thescientist13 Done & Done.
