### ISSUE TITLE
Document Manual testing strategy

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-docs#28]
[Testing Guide Wiki](https://github.com/ProvidenceGeeks/website-docs/wiki/Testing-Guide)
## Type of Change
- [x] New Documentation
- [x] Update to existing documentation
- [x] Other (please clarify below)

## Summary
- [x] Establish philosophy and strategy 
- [x] Scope of the test
- N/A Tool(s) used 
- [x] Test cases / [Acceptance Criteria](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design) 
- [x] Defect guidelines - update in the [issue template](https://github.com/ProvidenceGeeks/website-frontend/blob/develop/.github/ISSUE_TEMPLATE.md) in the front-end repository.
- [x] Walk-through session for above two with the team by 11/8

**Comment by saimatsumoto** [comment]
Manual Test is documented under and as a part of the feature test. @thescientist13

**Comment by thescientist13** [comment]
Looks good, thanks @saimatsumoto !
