### ISSUE TITLE
add an Environments section to README

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-docs#29]
## Type of Change
- [x] New Documentation
- [ ] Update to existing documentation
- [ ] Other (please clarify below)

## Summary

Let's add a section in the README called *Environment* that can document important URLs like
- Stage - http://stage.pvdgeeks.org
- Prod - http://www.pvdgeeks.org

**Comment by thescientist13** [comment]
Maybe after the Documentation section?

**Comment by saimatsumoto** [comment]
Just to confirm, the section is suggested to be added to the Issue Template, correct? @thescientist13

**Comment by thescientist13** [comment]
@saimatsumoto , oops.  Updated description.  this is for the README
