### ISSUE TITLE
Update App Design with new compact events list layout

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-docs#34]
## Type of Change
- [ ] New Documentation
- [x] Update to existing documentation
- [ ] Other (please clarify below)

## Summary

[Application Design wiki](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design) to include:
1. Layout change in events-list
2. Implementation of infinite scroll across all screen sizes
3. Twitter Share prepopulates default messages for events-list and blog posts.
4. Once the new images are available, update Hero-Banner section in Application Design with appropriate image(s) @saimatsumoto

**Comment by thescientist13** [comment]
<img width="1238" alt="screen shot 2017-11-10 at 5 55 27 pm" src="https://user-images.githubusercontent.com/895923/32682030-614db22c-c640-11e7-86a6-39bd326c1d0e.png">

**Comment by saimatsumoto** [comment]
4 will be tracked in #35; @thescientist13 if you can review the app design for Events List, will be great! thank you.

**Comment by thescientist13** [comment]
@saimatsumoto 
Looks good, just a couple observations

> Twitter Share prepopulates default messages for events-list and blog posts.

Should we document what the Facebook pre-pop message should be?  It seems only Twitter share message is documented

> When user scrolls at the end of the page, the page will load more blog contents.

Should it be _events_ content?

**Comment by saimatsumoto** [comment]
@thescientist13 thank you, updated with your tip.
