### ISSUE TITLE
Application Design for Desktop

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-docs#4]
## Type of Change
- [x] New Documentation
- [x] Update to existing documentation
- [x] Other (please clarify below)

## Summary

An Application Design is helpful for establishing the basic features, users stories, and look and feel of the project.  
1.  Overview
1.  Pages
1.  Components
1.  Services

The application design should have screens and images and link out to more technical documentation where appropriate.

## Related Issues
Mobile Design will be updated by 10/27 on #26

**Comment by thescientist13** [comment]
Mostly there
https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design

Just needs
1. [ ] images for each page and component
1. [ ] contact information 
1. [ ] header capabilities

cc: @saimatsumoto / @kpisano

**Comment by saimatsumoto** [comment]
[Application Design wiki](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design)

- [x] By 10/13: Update Header and Footer requirements/TODOs  
- [x] By 10/20: Update Hero Banner and Navigation requirements/TODOs 
- [x] By 10/27: Update Blog and Calendar requirements/TODOs

**Comment by saimatsumoto** [comment]
@thescientist13 Here are the proposed changes to Header and Footer requirements, please share any thoughts:

**Header**

Description: The header will contain the Providence Geeks logo/branding and navigations to three Providence Geeks Social Network pages.
Backend Service Dependencies: None
Capabilities:
1. Providence Geeks Logo is placed at the left side of the header.
1. Navigation: Show three Social Networking Services' icons on the top right of the header component
    * Facebook logo icon with link to the Facebook page - navigates to https://www.facebook.com/providencegeeks/ on click.
    * Twitter logo icon with link to Twitter profile - navigates to https://twitter.com/providencegeeks on click.
    * Slack log icon with links to the Slack page - navigates to https://providenceGeeks.slack.com on click.
1. Hover over each SNS icons displays a pop-up dialogue:
    * "Like Us" on Facebook icon	
    * "Follow Us" on twitter icon
    * "Join Us" on Slack
1. There will be no visual changes to the SNS logos when each asset is hovered over. 
1. The header design comply with the Styleguide (url) standards.
1. Orientation of the SNS logos: 
    * From left to right, Facebook, Twitter, and Slack. 
    * Collectively right-aligned
1. Margins:  //TODO: Need clarification

-------------
**Footer**

Description: The footer will contain the Providence Geeks logo/branding, copyright, and contact information
Backend Service Dependencies: None
Capabilities:
1. Show a copyright "copyright 2017 Providence Geeks":
1. Placed at the bottom of the footer, left-aligned
1. Providence Geeks Logo is placed at the left side of the footer.
1. Contact Info: 
    * Facebook logo icon with link to the Facebook page - navigates to https://www.facebook.com/providencegeeks/ on click.
    * Twitter logo icon with link to Twitter profile - navigates to https://twitter.com/providencegeeks on click.
    * Slack log icon with links to the Slack page - navigates to https://providenceGeeks.slack.com on click.
1. Show three Social Networking Services' icons in the footer component:
    * Facebook logo icon with link to the Facebook page - navigates to https://www.facebook.com/providencegeeks/ on click.
    * Twitter logo icon with link to Twitter profile - navigates to https://twitter.com/providencegeeks on click.
    * Slack log icon with links to the Slack page - navigates to https://providenceGeeks.slack.com on click.
1. SNS logos/text orientation: 
      * From left to right, Facebook, Twitter, and Slack.
      * Collectively center-aligned 
1. For the footer, hover-over message is inactive and will not be applied.
1. There will be no visual changes to the SNS logos when each asset is hovered over. 
1. The footer design comply with the Styleguide (url) standards.
1. Under the SNS logos, there are brief text descriptions:
      * "Like Us" on Facebook icon	
      * "Follow Us" on twitter icon
      * "Join Us" on Slack
      * These text are not clickable for CTA
* Margins:  //TODO: Need clarification

TODO: Image

**Comment by thescientist13** [comment]
@saimatsumoto 
This looks really solid to me!  (I just made some minor formatting tweaks to numerically order the top level A.C. for each of these)

Initial Thoughts
1.  We had discussed that using https://providenceGeeks.slack.com wasn't a user friendly experience, and that for now we should try and stick to the current strategy of using an explicit invitation link.  However, since we know it expires, and that means periodic manual code changes to update the link, I think there is an opportunity to make an issue in **website-backlog** to see if this could somehow be incorporated into the CMS such that the link can be updated and consumed by the frontend
1.  I will reach out to find out some best practices when using / not using fixed width units in a responsive based design
1.  For this requirement: _"Hover over each SNS icons displays a pop-up dialogue"_, Is the expectation just a [standard tooltip](https://developer.mozilla.org/en-US/docs/Defining_Cross-Browser_Tooltips), or something more robust?
1.  And to clarify the point above, in the **header** the tooltips will display on hover, but in the **footer** they will be displayed below the icon itself?
1.  More for @Peter-holyoke and I, but seems like there is a good opportunity for a "**social-links**" component (or whatever) just for grouping and managing the common functionality and styling of the three icons that can then be re-used in both the **header** and **footer**.  I see this more as an engineering opportunity per se, and not something that needs to be specifically captured in the application design, IMO.

**Comment by saimatsumoto** [comment]
@thescientist13 Thank you -  will update the bullet point style accordingly. 

1. Created https://github.com/ProvidenceGeeks/website-backlog/issues/5
2. To be followed up
3. As clarified - it's a standard tooltip 
4. Correct

**Comment by thescientist13** [comment]
Also @saimatsumoto , we will want to add a Hero Banner component.  I think Navigation can just go under the A.C. of the home page itself, which I think will essentially just need some minimal A.C. to "glue" components together to compose itself, if you will.

**Comment by saimatsumoto** [comment]
Thanks @thescientist13 I made changes below to [Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design)

1. Updated Header/Footer 
2. Added Hero Banner and Navigation bar

**Comment by saimatsumoto** [comment]
@thescientist13 @ekrasner1 @kpisano 
Please review the updates below - any feedback will be appreciated: 
FYI, there are still some outstanding questions that needs to be clarified at the Kick-off. 

### Updates/Review for:
[ ] Events page requirements
[ ] Blog page requirements
[ ] Blog details requirements

### Events 
* Description: Events page will be displayed when user navigates to the landing page; or when user toggle the Blog view to Events view by selecting “Events” on Navigation Bar. It is located under the
Navigation bar and above Footer.
* Backend Service Dependencies: Meetup.com 
* Capabilities:
1. Header: 
    1. Is named “Upcoming Events”
    1. Is left-aligned 
1. Two rows and three columns of events until reaching “Load More” button. 
    1. Column will remain three rows. 
1. Event images are static fed via Meetup API. //TODO
1. Event name is featured directly on the image, horizontally-bottom and vertically center-aligned. 
Clicking on Event Name navigates user to the Event website (Meetup.com).
1. Event Description 
    1. Featured below the Event image 
    1. Word Limit //TODO
    1. Aligned to the image width
    1. The contents are fed through Meetup.com
1. Date/Time is also fed through Meetup.com 
    1. Featured at the bottom-left of each event. 
1. Share Call-to-Action Arrow
    1. Featured at the bottom-right of each event.
    1. On hover over, dialog opens to suggest sharing the event link via Facebook or Twitter.  
    1. User clicks on the Facebook or Twitter icons in order to share.  
    1. Clicking on either icons will open a new pop up window.
    1. Navigates to a user’s Facebook or Twitter accounts; or
    1. Login page if not logged in.
1. Images are center-aligned within each event field.
1. Description texts are left-aligned within each event field. 
    1. Initially, no more than two more rows of events per page should be displayed until user clicks on “Load More” button. 
1. Load More button
    1. Is center-aligned within the component. 
    1. On click, two more rows of events will load. 
    1. If there are Three or less events left to load, only one more row will be loaded. 
    1. Hover over function is not active on the button.
1. Events are ordered chronologically (determined by Date/Time). 
1. Upcoming events with closer dates will be on the top. //TODO
1. Events page design complies with the Styleguide (url) standards.

### Blog 
* Description: Blog page will be displayed when user select the “Blog” on the Navigation Bar. It is located under the Navigation bar and above Footer.
* Backend Service Dependencies: WordPress 
* Capabilities:
1. There is no header for Blog view.
1. Two rows and three columns of events until reaching “Load More” button. 
    1. Column will remain three rows. 
1. Blog images are static, fed via WordPress API. //TODO
1. Each blog field contains an image, title, author, and date.
1. Blog title is featured directly on the image, horizontally-bottom and vertically center-aligned. 
1. Social icons (Facebook/Twitter) displayed on the top-right of each blog image.
    1. User clicks on the Facebook or Twitter icons in order to share blog link.  
    1. Clicking on either icons will open a new pop up window.
    1. Navigates to a user’s Facebook or Twitter accounts; or
    1. Login page if not logged in.
1. Blog excerpt/summary is located below each blog image.
    1. word limit //TODO
    1. Blog excerpts/summaries are fed via WP API //TODO, 2 sub-questions
1. “Read More” and an arrow 
     1. Located at the left-bottom of each blog field.
     1. Clicking on either assets will take to the blog details page 
     1. It will navigate on the same window/tab //TODO
1. Images are center aligned within each blog field.
1. Description texts are left-aligned within each blog field. 
1. Two rows and three columns of events until reaching “Load More” button. 
    1. Column will remain three rows. 
1. Load More button
    1. Is center-aligned within the component. 
    1. On click, two more rows of blogs will load. 
    1. If there are three or less blogs left to load, only one more row will be loaded. 
1. Hover-over function is not active on any of the assets on the blog page.
1. Blogs are listed and ordered chronologically
    1 .most recent post at the top, oldest at the bottom.
1. //TODO Tagging - label - through WP? clarify what it impacts, etc.  
1. Blog page design complies with the Styleguide (url) standards.

### Blog Details
* Description: Blog details page will contain the Hero-banner, Blog content, Social icons and other sharing methods. 
* Backend Service Dependencies: WordPress API
* Capabilities:
1. Hero banner: featured image on the blog page becomes the hero banner image.
    1. Image sizing //TODO
    1. Includes Blog title, author, and date.
1. Blog content is featured below the banner.
    1. Image - location could be determined by Content Manager //TODO	
    1. Caption fed via WordPress API. 
    1. SubHeadline is fed via WordPress API.
1. Share/Social Icons: 
    1. Icons are located at the left-top by the blog content, vertically oriented. 
    1. Facebook and Twitter icons
        1. User clicks on the Facebook or Twitter icons in order to share the blog link.  
        1. Clicking on either icons will open a new window.
        1. Navigates to a user’s Facebook or Twitter accounts; or
        1. Login page if not logged in.
    1. Clicking on the mail icon will open a new window to open user’s email. 
    1. Clicking on Print will open the Printing console to print the blog in PDF format.
    1. Icon sizes are responsive to the length  of the content.
1. Leave a comment //TODO
    1. Sign in needed via Social Network; or
    1. Leave comment directly on the details page:
    1. Leave comment form is located under the blog, followed by “Post” button.
    1. comments will be displayed under the blog. 
1. There will be no hover-over function on the blog details page.
1. Blog details page design complies with the Styleguide (url) standards.

**Comment by saimatsumoto** [comment]
Will close this issue as soon as getting one review at the least.

**Comment by thescientist13** [comment]
Taking a look thought, and overall looks very comprehensive!  Some general thoughts:
1. Should we have more descriptive name for these components instead of just **Events** and **Blog**?  How about Events / Blog List?  or something similar?  (I see it's called a Table in the tickets.  Let's just ensure consistency across our usages)
1. we don't have an events or blog page (yet).  We do have a Home page though.  I think we should re-word to remove page, in examples like this: 
    > Events ~*page*~ will be displayed when user navigates to the ~_landing_~ Home page; or when user toggle the Blog view to Events view by selecting “Events” on Navigation Bar. It is located under the
3. For backend services we should reference the services that our build / exposed to clients for this project.  So for the above it would be Events and Blog APIs, respectively> Backend Service Dependencies: Meetup.com.  There are multiple references to these external services throughout, so let's keep it closer to home and reference the services that are specifically being built for this project
    > Backend Service Dependencies: ~_Meetup.com_~ Events API

**Comment by saimatsumoto** [comment]
Thank you! @thescientist13 
1. Sounds great, will update the name to Events List and Blog Posts (FE ticket for Event Table was renamed as well). 
2. Updated - removed "page" from respective contents 
3. Noted, will do! 

[Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design)

**Comment by saimatsumoto** [comment]
Once below is completed, this issue will be closed. 
- [x] Images for each component to be added by 10/24

**Comment by thescientist13** [comment]
@saimatsumoto 
As the styleguide is its own task, I don't think it should be a dependency here per se?  That said, adding the images does seem appropriate.

**Comment by saimatsumoto** [comment]
Done - will close this issue upon review @thescientist13 @ekrasner1 @kpisano 

[Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design)
