### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-docs#5]
## Type of Change
- [x] New Documentation
- [ ] Update to existing documentation
- [x] Other (please clarify below)

## Summary

A Styleguide provides a way to capture the visual language, branding, and general UX best practices and conventions the project will follow.  The documentation will have
1.  Overview
1.  Logo / Branding
1.  ???
1.  ???
1.  ???

**Comment by kpisano** [comment]
Can also include:
3. Voice
4. Typography
5. Color Palette

**Comment by thescientist13** [comment]
good call @kpisano !

**Comment by thescientist13** [comment]
@bjepson 
Any thoughts on logo / branding you have would be super helpful!

**Comment by bjepson** [comment]
@thescientist13 we've always been very light on the branding/logo; we have a logo that's predominately type-only. That may need to change as we get more deliberate about things. I do like the addition of voice, typography, and palette that @kpisano suggested.

**Comment by saimatsumoto** [comment]
Final styleguide to include:
- [x] Overview
- [x] Logo/Branding
- [x] Color Theme - Color Palette
- [ ] Fonts - still to add one more font @ekrasner1 
- [x] Rules pertaining to logos and background - still to be added @ekrasner1

**Comment by thescientist13** [comment]
@saimatsumoto 
Is this complete now?  Looks like all the info is there
https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#styleguide

**Comment by saimatsumoto** [comment]
@thescientist13 Almost. Awaiting @ekrasner1 to update the font "Caslon" to "Canter".

**Comment by saimatsumoto** [comment]
Styleguide has been updated in Application Design page.
