### ISSUE TITLE
Technical Architecture: RFC

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-docs#9]
I am considering two changes to the current TA documentation wiki (see #3) and would be open to thoughts
https://github.com/ProvidenceGeeks/website-docs/wiki/Technical-Architecture

## [Frontend Webapp](https://github.com/ProvidenceGeeks/website-docs/wiki/Technical-Architecture#frontend-webapp)
Considering using [Polymer 3.0](https://www.polymer-project.org/blog/2017-08-22-npm-modules) for the project instead of React for a couple reasons
1.  Recent changes in Polymer's architecture, in particular moving to **npm** and embracing ECMAScript modules `import` / `export` make for some compelling reasons over previous versions
1.  Not sure how DOM intensive this project will be, since the general flow will be to just `GET` data from a backend, and display it.  I think this opens the door to more "experimental" opportunities to consider for the project
1.  It would be great to work more closely with a UI library that adheres closely web standards, but embracing web components (WC) with only a small glue / wrapper layer in between the developer and the WC API
1.  Still allows the codebase to be written in ES2015+ and use all the great JavaScript ecosystem tools like **webpack**, **babel**, etc
1.  Why not?  😃 

## [External Services](https://github.com/ProvidenceGeeks/website-docs/wiki/Technical-Architecture#wordpress-headless-cms)
Considering using [Contentful](https://www.contentful.com/) instead as the backing external service for the Blog, instead of Wordpress.  It would be worth [comparing](https://www.cloudcms.com/blog/post/129692706185/comparison-cloud-cms-vs-contentful) this against [Cloud CMS](https://www.cloudcms.com/) as well, but either of these have similar advantages over WP, such as
1.  RESTful CMS architecture by design first, which fits our use case perfectly
1.  SDK's available in a number of programming languages
1.  Why not?  😃 .... Well, cost in this case.  Contentful is not open source, and Contentful and Cloud CMS would have to be evaluated to see if there is free / cheap plan

I think it would be worth taking either of these for a brief spin first, as part of some basic discovery.  I have been doing [some work](https://github.com/thegreenhouseio/polymer-webapp-seed) with Polymer 3.0 already and have been really liking what I see so far.

Thoughts and feedback appreciated!

**Comment by bjepson** [comment]
Unfortunately, I don't have the technical experience with the tools and platforms you suggest, but I'm always in favor of open standards.

**Comment by thescientist13** [comment]
Going to stick with React and WordPress
